<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	  <RootNamespace>CS2_SimpleAdmin</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

  </PropertyGroup>

<PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <PublishTrimmed>true</PublishTrimmed>
        <DebuggerSupport>false</DebuggerSupport>
<!--        <GenerateDependencyFile>false</GenerateDependencyFile>-->
</PropertyGroup>

    <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.369">
      <PrivateAssets>none</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
        <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="MySqlConnector" Version="2.6.0" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageReference Include="System.Linq.Async" Version="7.0.1" />
    <PackageReference Include="ZLinq" Version="1.5.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CS2-SimpleAdminApi\CS2-SimpleAdminApi.csproj" />
  </ItemGroup>
<ItemGroup>
	<None Update="lang\**\*.*" CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>

	<ItemGroup>
    <None Update="Database\Migrations\**\*.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="admin_help.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="MenuManagerApi">
			<HintPath>3rd_party\MenuManagerApi.dll</HintPath>
            <Private>False</Private>
		</Reference>
	</ItemGroup>

</Project>
